{{- if .Values.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mpchess.fullname" . }}-config
  labels:
    {{- include "mpchess.labels" . | nindent 4 }}
data:
  config.jsonc: |
    {{- .Values.config.content | nindent 4 }}
{{- end }}
