apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mpchess.fullname" . }}
  labels:
    {{- include "mpchess.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "mpchess.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mpchess.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.securityContext.enabled }}
      securityContext:
        {{- toYaml .Values.securityContext.pod | nindent 8 }}
      {{- end }}
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- if .Values.securityContext.enabled }}
          securityContext:
            {{- toYaml .Values.securityContext.container | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ include "mpchess.portName" . }}
              containerPort: {{ .Values.server.port }}
              protocol: TCP
          env:
            - name: MPCHESS_PORT
              value: {{ .Values.server.port | toString | quote }}
            {{- if .Values.server.fen }}
            - name: MPCHESS_FEN
              value: {{ .Values.server.fen | quote }}
            {{- end }}
            {{- if .Values.server.allowedOrigins }}
            - name: MPCHESS_ALLOWED_ORIGINS
              value: {{ .Values.server.allowedOrigins | quote }}
            {{- end }}
            {{- if and .Values.server.prefix (ne .Values.server.prefix "/") }}
            - name: MPCHESS_PREFIX
              value: {{ .Values.server.prefix | quote }}
            {{- end }}
            {{- if .Values.server.debug }}
            - name: MPCHESS_DEBUG
              value: {{ .Values.server.debug | toString | quote }}
            {{- end }}
            {{- if .Values.tls.enabled }}
            - name: MPCHESS_CERT
              value: "/etc/tls/tls.crt"
            - name: MPCHESS_KEY
              value: "/etc/tls/tls.key"
            {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ include "mpchess.portName" . }}
              {{- if .Values.tls.enabled }}
              scheme: HTTPS
              {{- end }}
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: {{ include "mpchess.portName" . }}
              {{- if .Values.tls.enabled }}
              scheme: HTTPS
              {{- end }}
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            {{- if .Values.config.enabled }}
            - name: config
              mountPath: /app/config.jsonc
              subPath: config.jsonc
            {{- end }}
            {{- if .Values.tls.enabled }}
            - name: tls
              mountPath: /etc/tls/tls.crt
              subPath: tls.crt
              readOnly: true
            - name: tls
              mountPath: /etc/tls/tls.key
              subPath: tls.key
              readOnly: true
            {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
        {{- if .Values.config.enabled }}
        - name: config
          configMap:
            name: {{ include "mpchess.fullname" . }}-config
        {{- end }}
        {{- if .Values.tls.enabled }}
        - name: tls
          secret:
            secretName: {{ .Values.tls.secretName }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
