{{- if and (ne .Values.gateway.type "none") (eq .Values.gateway.type "ingress") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mpchess.fullname" . }}
  labels:
    {{- include "mpchess.labels" . | nindent 4 }}
  {{- if or .Values.gateway.ingressAnnotations (and (ne .Values.gateway.pathPrefix "/") .Values.gateway.ingressController) }}
  annotations:
    {{- range $key, $value := .Values.gateway.ingressAnnotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- if and (ne .Values.gateway.pathPrefix "/") (eq .Values.gateway.ingressController "traefik") }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ include "mpchess.fullname" . }}-strip@kubernetescrd
    {{- end }}
    {{- if and (ne .Values.gateway.pathPrefix "/") (eq .Values.gateway.ingressController "nginx") }}
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    {{- end }}
  {{- end }}
spec:
  {{- if .Values.gateway.ingressClassName }}
  ingressClassName: {{ .Values.gateway.ingressClassName }}
  {{- end }}
  {{- if .Values.gateway.tlsSecretName }}
  tls:
    - hosts:
        - "{{ .Values.gateway.host }}"
      secretName: {{ .Values.gateway.tlsSecretName }}
  {{- end }}
  rules:
    - host: "{{ .Values.gateway.host }}"
      http:
        paths:
          - path: {{ if and (ne .Values.gateway.pathPrefix "/") (eq .Values.gateway.ingressController "nginx") }}"{{ .Values.gateway.pathPrefix }}(/|$)(.*)"{{ else }}{{ .Values.gateway.pathPrefix }}{{ end }}
            pathType: {{ if and (ne .Values.gateway.pathPrefix "/") (eq .Values.gateway.ingressController "nginx") }}ImplementationSpecific{{ else }}Prefix{{ end }}
            backend:
              service:
                name: {{ include "mpchess.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
