{{- if and (ne .Values.gateway.type "none") (eq .Values.gateway.type "ingress") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mpchess.fullname" . }}
  labels:
    {{- include "mpchess.labels" . | nindent 4 }}
  {{- if .Values.gateway.ingressAnnotations }}
  annotations:
    {{- range $key, $value := .Values.gateway.ingressAnnotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- if .Values.gateway.ingressClassName }}
  ingressClassName: {{ .Values.gateway.ingressClassName }}
  {{- end }}
  {{- if .Values.gateway.tlsSecretName }}
  tls:
    - hosts:
        - "{{ .Values.gateway.host }}"
      secretName: {{ .Values.gateway.tlsSecretName }}
  {{- end }}
  rules:
    - host: "{{ .Values.gateway.host }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "mpchess.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
