{{- $prefix := include "mpchess.pathPrefix" . }}
{{- if and (eq .Values.gateway.type "ingress") (ne $prefix "/") (eq .Values.gateway.ingressController "traefik") }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "mpchess.fullname" . }}-strip
  labels:
    {{- include "mpchess.labels" . | nindent 4 }}
spec:
  stripPrefix:
    prefixes:
      - {{ $prefix }}
{{- end }}
