apiVersion: v1
kind: Service
metadata:
  name: {{ include "mpchess.fullname" . }}
  labels:
    {{- include "mpchess.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ include "mpchess.portName" . }}
      protocol: TCP
      name: {{ include "mpchess.portName" . }}
  selector:
    {{- include "mpchess.selectorLabels" . | nindent 4 }}
